#!/usr/bin/env bash
#
#Author: Anil Narasimhappa
#Date: 14/08/2021
#Version: 0.2
#Location: Melbourne, Australia
#gx is the utility to set gcloud projects in gcloud config.
#commands usages:
#gx         : to list the gcloud projects
#gx <name>  : set the project name in the config file
#gx -h      : help

#Function to display commands
help() {
    echo "gx                      : to list the projects"
    echo "gx <name>               : set the project name in the gcloud config"
    #echo "gx z                 : to list the zones"
    #echo "gx z <name>          : set the zone in the gcloud config"
    #echo "gx r               : to list the region"
    #echo "gx r <name>        : set the region in the gcloud config"
    echo "gx -h                   : help"
    echo "gx -l                   : List gcloud configurations"
    echo "gx -a                   : Activate a gcloud configuration"
}

#Function to list projects accessible by the active account
list_projects() {
gcloud projects list
}

#Function to set project
set_projects() {
  gcloud config set project "${1}"
}

#Function to list configurations
configurations_list(){
    gcloud config configurations list

}

#Function to activate configurations
configurations_activate(){
    if [[ "$2" == '' ]]; then
        echo "enter the configuration name"
    else
        gcloud config configurations activate "${2}"
    fi
}

#Condition to check the input value
if [[ "$#" -eq 0 ]]; then
    list_projects
elif [ "$1" = '-h' ] || [ "$1" = '-help' ] || [ "$1" = '--h' ] || [ "$1" = '--help' ]; then
     help
elif [[ "$1" = '-l' ]]; then
     configurations_list
elif [[ "$1" = '-a' ]]; then
    configurations_activate "$@"
else
    set_projects "${1}"
fi
