#!/usr/bin/env bash
#
#Author: Anil Narasimhappa
#Date: 23/08/2019
#Version: 0.1
#Location: Melbourne, Australia
#gcex is the utility to set gcloud projects in gcloud config.
#commands usages:
#gcex         : to list the gcloud projects
#gcex <name>  : set the project name in the config file
#gxec -h      : help

#list projects accessible by the active account
list_projects() {
gcloud projects list
}

set_projects() {
  gcloud config set project "${1}"
}

help() {
    echo "gcex                      : to list the projects"
    echo "gcex <name>               : set the project name in the gcloud config"
    #echo "gcex z                 : to list the zones"
    #echo "gcex z <name>          : set the zone in the gcloud config"
    #echo "gcex r               : to list the region"
    #echo "gcex r <name>        : set the region in the gcloud config"
    echo "gxec -h                   : help"
}
if [[ "$#" -eq 0 ]]; then
    list_projects
elif [[ "$1" = '-h' ]]; then
     help
else
    set_projects "${1}"
fi
