#!/usr/bin/env bash
#
#Author: Anil Narasimhappa
#Date: 23/08/2019
#Version: 0.1
#Location: Melbourne, Australia
#gcex is the utility to set gcloud projects in gcloud config.
#commands usages:
#gcex         : to list the gcloud projects
#gcex <name>  : set the project name in the config file
#gxec -h      : help

#Function to display commands
help() {
    echo "gcex                      : to list the projects"
    echo "gcex <name>               : set the project name in the gcloud config"
    #echo "gcex z                 : to list the zones"
    #echo "gcex z <name>          : set the zone in the gcloud config"
    #echo "gcex r               : to list the region"
    #echo "gcex r <name>        : set the region in the gcloud config"
    echo "gxec -h                   : help"
    echo "gxec -l                   : List gcloud configurations"
    echo "gxec -a                   : Activate a gcloud configuration"
}

#Function to list projects accessible by the active account
list_projects() {
gcloud projects list
}

#Function to set project
set_projects() {
  gcloud config set project "${1}"
}

#Function to list configurations
configurations_list(){
    gcloud config configurations list

}

#Function to activate configurations
configurations_activate(){
    if [[ "$2" == '' ]]; then
        echo "enter the configuration name"
    else
        gcloud config configurations activate "${2}"
    fi
}

#Condition to check the input value
if [[ "$#" -eq 0 ]]; then
    list_projects
elif [ "$1" = '-h' ] || [ "$1" = '-help' ]; then
     help
elif [[ "$1" = '-l' ]]; then
     configurations_list
elif [[ "$1" = '-a' ]]; then
    configurations_activate "$@"
else
    set_projects "${1}"
fi
